### ISSUE TITLE
Don't List JS Files

### ISSUE THREAD

**Issue by joezimjs** [ludoviclefevre/hexo-generator-seo-friendly-sitemap#2]
There are some .js files showing up in page-sitemap.xml. Could you create a way to exclude certain extensions? Do you know why JS files are being shown in the first place?

**Comment by joezimjs** [comment]
BTW, the listed JS files are in my static assets folder.

**Comment by ludoviclefevre** [comment]
Hi,

Well spotted. I made a mistake in page sitemap generation. Correction will be released soon.

Thanks

Ludovic

**Comment by ludoviclefevre** [comment]
v0.012 released, you can update hexo-generator-seo-friendly-sitemap package

**Comment by joezimjs** [comment]
For whatever reason, it's not letting me update to 0.0.12 right now. I'll check on it later. I see it in the npm registry: https://www.npmjs.com/package/hexo-generator-seo-friendly-sitemap
So I don't know why it wouldn't let me.

**Comment by ludoviclefevre** [comment]
Did you try to update again? It works for me.

**Comment by joezimjs** [comment]
Works now. Thanks!
