### ISSUE TITLE
Frontmatter option to exclude a content from the sitemap

### ISSUE THREAD

**Issue by vhf** [ludoviclefevre/hexo-generator-seo-friendly-sitemap#3]
What would you think about an frontmatter option (e.g. `nositemap: true`) to exclude a page/post?

Tell me what you think, I could take a stab at it if you don't have time but still have interest for such a PR.

**Comment by ludoviclefevre** [comment]
Hi,

in there's already an undocumented frontmatter option to exclue page or post: `sitemap: false`

I think I didn't test it could you tell if it works for you.

Thanks.

**Comment by vhf** [comment]
Works great, merci beaucoup!
