### ISSUE TITLE
请问可以添加不受hexo渲染的自定义页面到sitemap吗？

### ISSUE THREAD

**Issue by W4J1e** [ludoviclefevre/hexo-generator-seo-friendly-sitemap#35]
rt，在hexo博客中嵌入了一些不被渲染的独立html页面，请问有什么办法让它们添加到sitemap中？

**Comment by Leao9203** [comment]
建议尝试在 Markdown 中内嵌 html，Hexo 是可以在 .md 文件中关闭主题渲染的。
