### ISSUE TITLE
關於sitemap提交

### ISSUE THREAD

**Issue by jerryc127** [ludoviclefevre/hexo-generator-seo-friendly-sitemap#36]
這個插件生成後的 sitemap.xml 是一個地圖索引
那還是直接提交這個 sitemap.xml 到站長平臺麽？
還是要將 索引 内的幾個xml 分別提交？

**Comment by W4J1e** [comment]
百度不支持索引型sitemap，所以分开提交。谷歌和360站长平台支持索引型sitemap，所以提交sitemap.xml的链接就可以了。

**Comment by jerryc127** [comment]
好 感谢回答
