### ISSUE TITLE
SiteMap URL

### ISSUE THREAD

**Issue by xxf1995** [ludoviclefevre/hexo-generator-seo-friendly-sitemap#6]
Hi, I am new to sitemaps.
Using this plugin generated a several files. What are they for?
Also, I have no idea how to let the generator generates the right URL to replace `your site`.
```
    <sitemap>
        <loc>http://yoursite.com/post-sitemap.xml</loc>
        <lastmod>2016-04-19T01:19:19.000Z</lastmod>
```

**Comment by ludoviclefevre** [comment]
Hi,

Quote from : https://support.google.com/webmasters/answer/156184?hl=en

> A sitemap is a file where you can list the web pages of your site to tell Google and other search engines about the organization of your site content. Search engine web crawlers like Googlebot read this file to more intelligently crawl your site.

To replace `yoursite.com`, you need to edit the _config.yml file in hexo project root and set `url` property to your website url.

I hope this will help.
