### ISSUE TITLE
custom layout pages missing from sitemap

### ISSUE THREAD

**Issue by mef** [ludoviclefevre/hexo-generator-seo-friendly-sitemap#7]
As a side-effect from #2, any page that is not a post and doesn't use the `page` layout doesn't show up in the sitemaps.

This is a problem whenever custom layouts are defined.

Using the following check [here](https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap/blob/master/lib/page.js#L11) should solve the problem:

````javascript
if (page.layout === 'false') {
````
instead of 

````javascript
if (page.layout !== 'page') {
````

**Comment by ludoviclefevre** [comment]
well spotted. I will fix this problem. thanks

**Comment by ludoviclefevre** [comment]
Check fixed
